"""
CLI entry point for the Tech Support Copilot POC.

Run from the project root::

    python main.py

The CLI accepts customer messages typed by the rep, runs them through the
agentic orchestrator, and prints colour-coded output showing tool calls,
approval prompts, critic results, and the final suggestion.

Special commands
----------------
/trace      Print the path of the current JSONL trace file.
/evidence   Dump the evidence log accumulated this session.
/quit       End the session and close the trace file.
"""
from __future__ import annotations

import argparse
import sys
import json

import config
from agent.orchestrator import Orchestrator
from llm.bedrock_client import BedrockClient
from llm.customer_llm import CustomerLLM
from observability.tracer import Tracer
from tools import build_default_registry
from tools.base import Tool

from rich.console import Console
from rich.panel import Panel
from rich.rule import Rule
from rich.text import Text
from rich import box

console = Console()

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------

_BANNER_SIMULATE = """
[bold cyan]╔══════════════════════════════════════════════════════╗[/bold cyan]
[bold cyan]║      Tech Support Copilot  —  POC (Haiku 4.5)        ║[/bold cyan]
[bold cyan]╚══════════════════════════════════════════════════════╝[/bold cyan]
[dim]Simulation mode: customer messages are generated by AI. Just watch.[/dim]
[dim]Press Ctrl+C to quit.[/dim]
"""

_BANNER_MANUAL = """
[bold cyan]╔══════════════════════════════════════════════════════╗[/bold cyan]
[bold cyan]║      Tech Support Copilot  —  POC (Haiku 4.5)        ║[/bold cyan]
[bold cyan]╚══════════════════════════════════════════════════════╝[/bold cyan]
[dim]Type the customer's message and press Enter.[/dim]
[dim]Special commands: /trace  /evidence  /quit[/dim]
"""


# ---------------------------------------------------------------------------
# Event hook  (displays mid-loop events as they happen)
# ---------------------------------------------------------------------------

def _make_event_hook(tracer: Tracer) -> object:
    """Return a closure that pretty-prints orchestrator events to the console."""

    def event_hook(event: str, data: dict) -> None:
        if event == "tool_call":
            name = data.get("name", "?")
            inputs = data.get("inputs", {})
            # Compact single-line repr of inputs
            inputs_str = json.dumps(inputs, default=str)
            if len(inputs_str) > 100:
                inputs_str = inputs_str[:97] + "..."
            console.print(f"  [cyan]🔧 Tool call:[/cyan] [bold]{name}[/bold]({inputs_str})")

        elif event == "tool_result":
            name = data.get("name", "?")
            result = data.get("result", {})
            if result.get("success"):
                raw = result.get("data")
                if isinstance(raw, dict):
                    snippet = json.dumps(raw, default=str)
                else:
                    snippet = str(raw)
                if len(snippet) > 120:
                    snippet = snippet[:117] + "..."
                latency = result.get("latency_ms", 0)
                console.print(
                    f"  [green]✅ Result ({latency} ms):[/green] {snippet}"
                )
            else:
                error = result.get("error", "unknown error")
                console.print(f"  [red]❌ {name} failed:[/red] {error}")

        elif event == "critic":
            passed = data.get("passed", True)
            feedback = data.get("feedback", "")
            uncited = data.get("uncited_claims", [])
            if passed:
                console.print(f"  [green]🧐 Critic: PASSED[/green] — {feedback}")
            else:
                console.print(f"  [yellow]🧐 Critic: FAILED[/yellow] — {feedback}")
                for claim in uncited:
                    console.print(f"     [yellow]• {claim}[/yellow]")
            tracer.critic(data)

    return event_hook


# ---------------------------------------------------------------------------
# Approval callback
# ---------------------------------------------------------------------------

def _make_cli_approver(tracer: Tracer) -> object:
    """Return a closure that prompts the operator for high-risk tool approval."""

    def cli_approver(tool: Tool, inputs: dict) -> bool:
        tracer.approval_prompt(tool.name, inputs)
        console.print()
        console.print(
            Panel(
                f"[bold]Tool:[/bold] {tool.name}\n"
                f"[bold]Inputs:[/bold] {json.dumps(inputs, default=str)}\n"
                f"[bold]Description:[/bold] {tool.description[:120]}",
                title="[yellow]⚠  High-risk tool approval required[/yellow]",
                border_style="yellow",
                box=box.ROUNDED,
            )
        )
        try:
            answer = console.input("  Approve? [y/N]: ").strip().lower()
        except EOFError:
            answer = "n"
        approved = answer == "y"
        tracer.approval_decision(tool.name, approved)
        if approved:
            console.print("  [green]Approved.[/green]")
        else:
            console.print("  [red]Rejected.[/red]")
        console.print()
        return approved

    return cli_approver


# ---------------------------------------------------------------------------
# Special commands
# ---------------------------------------------------------------------------

def _handle_command(cmd: str, orchestrator: Orchestrator, tracer: Tracer) -> None:
    """Dispatch a /command entered by the rep."""
    cmd = cmd.strip().lower()

    if cmd == "/trace":
        console.print(f"[dim]Trace file: {tracer.filepath}[/dim]")

    elif cmd == "/evidence":
        evidence = orchestrator.memory.evidence_log
        if not evidence:
            console.print("[dim]No evidence gathered yet.[/dim]")
        else:
            console.print(
                Panel(
                    orchestrator.memory.summarize_evidence(),
                    title=f"[cyan]Evidence Log ({len(evidence)} entries)[/cyan]",
                    border_style="cyan",
                )
            )

    elif cmd == "/quit":
        console.print("[dim]Ending session...[/dim]")
        tracer.close()
        sys.exit(0)

    else:
        console.print(
            f"[red]Unknown command:[/red] {cmd}  "
            "[dim](available: /trace  /evidence  /quit)[/dim]"
        )


# ---------------------------------------------------------------------------
# Loop helpers
# ---------------------------------------------------------------------------

def _run_simulate_loop(
    orchestrator: Orchestrator,
    customer_llm: "CustomerLLM",
    event_hook: object,
    max_turns: int,
    tracer: Tracer,
) -> None:
    """Fully automated loop: customer LLM generates all messages."""
    console.print("[dim]  Generating opening customer message...[/dim]")
    try:
        user_input = customer_llm.opening_message()
    except Exception as exc:  # noqa: BLE001
        console.print(f"[red]Customer LLM failed on opening message:[/red] {exc}")
        return

    for turn in range(1, max_turns + 1):
        console.print(
            Panel(
                Text(user_input, overflow="fold"),
                title="[bold magenta]Customer  (AI-generated)[/bold magenta]",
                border_style="magenta",
                box=box.ROUNDED,
            )
        )
        console.print("[dim]  Agent thinking...[/dim]")
        console.print()

        try:
            response = orchestrator.handle_turn(user_input, event_hook=event_hook)
        except Exception as exc:  # noqa: BLE001
            tracer.error("Unhandled orchestrator exception", str(exc))
            console.print(f"[red]Unexpected error:[/red] {exc}")
            break

        console.print()
        console.print(
            Panel(
                Text(response, overflow="fold"),
                title="[bold green]Rep Suggestion[/bold green]",
                border_style="green",
                box=box.ROUNDED,
            )
        )
        console.print()

        if turn >= max_turns:
            console.print(f"[dim]Simulation complete after {max_turns} turns.[/dim]")
            break

        console.print("[dim]  Generating next customer message...[/dim]")
        try:
            user_input = customer_llm.reply(response)
        except Exception as exc:  # noqa: BLE001
            console.print(f"[red]Customer LLM failed on reply:[/red] {exc}")
            break


def _run_manual_loop(
    orchestrator: Orchestrator,
    event_hook: object,
    tracer: Tracer,
) -> None:
    """Interactive loop: human types each customer message."""
    while True:
        try:
            user_input = console.input("[bold cyan]Customer>[/bold cyan] ").strip()
        except EOFError:
            break

        if not user_input:
            continue

        if user_input.startswith("/"):
            _handle_command(user_input, orchestrator, tracer)
            continue

        console.print()
        console.print("[dim]  Agent thinking...[/dim]")
        console.print()

        try:
            response = orchestrator.handle_turn(user_input, event_hook=event_hook)
        except Exception as exc:  # noqa: BLE001
            tracer.error("Unhandled orchestrator exception", str(exc))
            console.print(f"[red]Unexpected error:[/red] {exc}")
            continue

        console.print()
        console.print(
            Panel(
                Text(response, overflow="fold"),
                title="[bold green]Rep Suggestion[/bold green]",
                border_style="green",
                box=box.ROUNDED,
            )
        )
        console.print()


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def main() -> None:
    """Start the interactive tech support copilot session."""
    parser = argparse.ArgumentParser(description="Tech Support Copilot POC")
    parser.add_argument(
        "--manual",
        action="store_true",
        help="Accept customer messages from keyboard instead of the customer LLM (default: simulate).",
    )
    parser.add_argument(
        "--turns",
        type=int,
        default=5,
        metavar="N",
        help="Number of simulated turns before auto-quitting (default: 5).",
    )
    args = parser.parse_args()
    args.simulate = not args.manual

    console.print(_BANNER_SIMULATE if args.simulate else _BANNER_MANUAL)

    # ------------------------------------------------------------------
    # Bootstrap
    # ------------------------------------------------------------------
    try:
        registry = build_default_registry()
        bedrock = BedrockClient()
        tracer = Tracer()
        customer_llm = CustomerLLM() if args.simulate else None
    except Exception as exc:  # noqa: BLE001
        console.print(f"[red]Startup failed:[/red] {exc}")
        sys.exit(1)

    event_hook = _make_event_hook(tracer)
    cli_approver = _make_cli_approver(tracer)

    orchestrator = Orchestrator(
        bedrock=bedrock,
        registry=registry,
        tracer=tracer,
        approver=cli_approver,
    )

    console.print(
        f"[dim]Session started. Trace: {tracer.filepath}[/dim]"
    )
    console.print(
        f"[dim]Tools loaded: {', '.join(registry.list_names())}[/dim]"
    )
    if args.simulate:
        console.print(
            f"[dim]Simulate mode ON — customer LLM will generate {args.turns} turns. Pass --manual to type messages yourself.[/dim]"
        )
    console.print()

    # ------------------------------------------------------------------
    # REPL — two completely separate branches
    # ------------------------------------------------------------------
    try:
        if args.simulate:
            _run_simulate_loop(orchestrator, customer_llm, event_hook, args.turns, tracer)
        else:
            _run_manual_loop(orchestrator, event_hook, tracer)
    except KeyboardInterrupt:
        pass
    finally:
        tracer.close()
        console.print()
        console.print("[dim]Session ended. Goodbye.[/dim]")


if __name__ == "__main__":
    main()
